### ISSUE TITLE
Logging in broken on `v0.19` instance with emojis enabled.

### ISSUE THREAD

**Issue by dessalines** [MV-GH/LemmyBackwardsCompatibleAPI#10]
I'll post logs shortly, but the error is `Illegal input: Field 'id' is required for type with serial name 'it. vercruysse.lemmyapi.v0x19.datatypes.CustomEmojiKeyword', but was missing at path: $.custom_emojis[0].keywords[0]`

**Comment by MV-GH** [comment]
Hmm CustomEmojiId is typealias

**Comment by MV-GH** [comment]
Can you tell me on which API endpoint this happens

edit: I think its /site?

**Comment by dessalines** [comment]
Yep it's site. 

Linked jerboa issue: https://github.com/dessalines/jerboa/issues/1294
