### ISSUE TITLE
Expose httpClient configuration 

### ISSUE THREAD

**Issue by MV-GH** [MV-GH/LemmyBackwardsCompatibleAPI#20]
Not sure yet how to best achieve this, but i want the consumer be able to fully modify httpClient but it should still have the current config defaults

**Comment by dessalines** [comment]
Not sure how feasible it is, but I'd have no problem moving the entire http client into this library. I know that sometimes isn't preferred, especially if there are a variety of HTTP clients for a given stack, but OkHTTP seems to be pretty much the standard now.

**Comment by MV-GH** [comment]
I don't follow exactly, this lib has its own httpClient (it even creates ones per instance, due to auth as its baked into the client).
Each platform (JVM, JS, native) has it own "engine" which ktor nomenclature for the actual underlying httpClient. For JVM that is OkHTTP. 

So what I want to achieve is that it would be possible to pass a Ktor httpClient (which is basically a config around the actual httpClient) but I still need to apply some defaults somehow to this httpClient. Some settings need to be set so that this lib will function correctly. Mostly for the Json parsing.

Once this is possible we will be able to create the okHttp client in Jerboa, and pass this into the LemmyApi instances. So that we only have one okHttp instance.
