### ISSUE TITLE
How to properly auto-generate routes?

### ISSUE THREAD

**Issue by dessalines** [MV-GH/LemmyBackwardsCompatibleAPI#21]
I'd like to add the `ListPostLikes` and `ListCommentLikes` routes in order to add the Admin View Votes functionality to jerboa, but I'm not seeing any instructions for how to do that in the README, or any scripts, like we used to with jerboa `copy_generated_types.sh`. 

Should I do a PR to add them manually for now?

**Comment by MV-GH** [comment]
Sure, did those endpoints get added only recently? They are automatically generated based on the lemmy-js-client. there is a autogenerated submodule which contains all the generator scripts.

**Comment by MV-GH** [comment]
I have added these endpoints now, but I still need to expand the documentation regarding this information. So, I ll leave this open for now

**Comment by dessalines** [comment]
Sweet, thx!
