### ISSUE TITLE
Have demo app?

### ISSUE THREAD

**Issue by zoujiaqing** [MV-GH/LemmyBackwardsCompatibleAPI#72]
Hi.

Thank you for this project work!

I want create an app for both ios and android platform.

Has a demo application?

**Comment by dessalines** [comment]
Jerboa is the main user of this. If you'd like to make that multi-platform, (as that's already a nearly complete lemmy app) that'd be hugely helpful.

**Comment by MV-GH** [comment]
Yeah you can look at Jerboa to see how to use it. But imo its pretty straightforward, if there is documentation missing. You can raise a issue. I will look at adding it then.
